@Players.Api_HostAddress = https://localhost:44303/players

GET {{Players.Api_HostAddress}}
Accept: application/json

###

POST {{Players.Api_HostAddress}}
Accept: application/json
Content-Type: application/json

{
  "phone": "+441234567890"
}

###

PUT {{Players.Api_HostAddress}}/name
Accept: application/json
Content-Type: application/json

{
  "name": "Player 1"
}

###

PUT {{Players.Api_HostAddress}}/image
Accept: application/json
Content-Type: application/json

{
  "imageUrl": "some-image-url"
}
